"DOTAUnits"
{
  "archer_tower"
  {
    "Model"                     "models/heroes/drow/drow_base.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_drow/drow_base_attack.vpcf"
    "ProjectileSpeed"           "2500"
    "SoundSet"                  "Hero_DrowRanger"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_drowranger.vsndevts"

    "Ability1"                  "upgrade_gunner_tower"
    "Ability2"                  ""

    "AttackDamageMin"           "1"
    "AttackDamageMax"           "2"
    "AttackRange"               "450"
    "AttackAcquisitionRange"    "450"
    "AttackRate"                "1.0"
    "AttackAnimationPoint"      "0.65"
  
    "AttackType"                "pierce"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "25"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"

    "Creature"
    {
      "AttachWearables"
      {
        "1"  { "ItemDef" "77" } // Weapon
        "2"  { "ItemDef" "79" } // Quiver
        "3"  { "ItemDef" "267"} // Head
        "4"  { "ItemDef" "76" } // Back
        "5"  { "ItemDef" "80" } // Shoulder
        "6"  { "ItemDef" "78" } // Legs
        "7"  { "ItemDef" "75" } // Arms
      }
    }
  }
  
  "gunner_tower"
  {
    "Model"                     "models/heroes/sniper/sniper.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_sniper/sniper_base_attack.vpcf"
    "ProjectileSpeed"           "2500"
    "SoundSet"                  "Hero_Sniper"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts"

    "Ability1"                  "upgrade_watch_tower"
    "Ability2"                  "upgrade_cannon_tower"

    "AttackDamageMin"           "3"
    "AttackDamageMax"           "5"
    "AttackRange"               "600"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.8"
    "AttackAnimationPoint"      "0.17"
  
    "AttackType"                "pierce"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "35"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"

    "Creature"
    {
      "AttachWearables"
      {
        "1"  { "ItemDef" "281" }  // Weapon
        "2"  { "ItemDef" "283" }  // Head
        "3"  { "ItemDef" "284" }  // Shoulder
        "4"  { "ItemDef" "285" }  // Arms
        "5"  { "ItemDef" "282" }  // Back
      }
    }
  }
  
  "watch_tower"
  {
    "Model"                     "models/orc/wooden_sentry_tower001.vmdl"
    "ModelScale"                "0.4"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_mirana/mirana_base_attack.vpcf"
    "ProjectileSpeed"           "2500"
    "SoundSet"                  "Hero_Mirana"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_mirana.vsndevts"

    "Ability1"                  "upgrade_guard_tower"
    "Ability2"                  ""

    "AttackDamageMin"           "10"
    "AttackDamageMax"           "15"
    "AttackRange"               "700"
    "AttackAcquisitionRange"    "700"
    "AttackRate"                "0.75"
    "AttackAnimationPoint"      "0.0"
  
    "AttackType"                "pierce"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }
  
  "guard_tower"
  {
    "Model"                     "models/props_structures/radiant_tower002.vmdl"
    "ModelScale"                "0.7"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/base_attacks/ranged_tower_good.vpcf"
    "ProjectileSpeed"           "2500"
    "SoundSet"                  "Tower.Water"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            ""

    "Ability1"                  "upgrade_ward_tower"
    "Ability2"                  ""

    "AttackDamageMin"           "20"
    "AttackDamageMax"           "25"
    "AttackRange"               "700"
    "AttackAcquisitionRange"    "700"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.0"
  
    "AttackType"                "pierce"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "250"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }
  
  "ward_tower"
  {
    "Model"                     "models/items/wards/celestial_observatory/celestial_observatory.vmdl"
    "ModelScale"                "1.3"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_witchdoctor/witchdoctor_base_attack.vpcf"
    "ProjectileSpeed"           "2500"
    "SoundSet"                  "Hero_WitchDoctor"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            ""

    "Ability1"                  "upgrade_ultimate_ward_tower"
    "Ability2"                  ""

    "AttackDamageMin"           "110"
    "AttackDamageMax"           "115"
    "AttackRange"               "800"
    "AttackAcquisitionRange"    "800"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.0"
  
  "AttackType"                "pierce"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "1500"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }
  
  "ultimate_ward_tower"
  {
    "Model"                     "models/items/wards/esl_wardchest_ward_of_foresight/esl_wardchest_ward_of_foresight.vmdl"
    "ModelScale"                "1.7"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "2500"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            ""

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "360"
    "AttackDamageMax"           "365"
    "AttackRange"               "800"
    "AttackAcquisitionRange"    "800"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.0"
  
    "AttackType"                "pierce"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "3000"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }
  
  "cannon_tower"
  {
    "Model"                     "models/creeps/lane_creeps/creep_good_siege/creep_good_siege.vmdl"
    "ModelScale"                "0.5"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/base_attacks/ranged_siege_good.vpcf"
    "ProjectileSpeed"           "2500"
    "SoundSet"                  "Creep_Good_Engine"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            ""

    "Ability1"                  "upgrade_bombard_tower"
    "Ability2"                  ""

    "AttackDamageMin"           "10"
    "AttackDamageMax"           "12"
    "AttackRange"               "700"
    "AttackAcquisitionRange"    "700"
    "AttackRate"                "2"
    "AttackAnimationPoint"      "0.7"
  
    "AttackType"                "siege"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }
  
  "bombard_tower"
  {
    "Model"                     "models/creeps/lane_creeps/creep_bad_siege/creep_bad_siege.vmdl"
    "ModelScale"                "0.6"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/base_attacks/ranged_siege_bad.vpcf"
    "ProjectileSpeed"           "2500"
    "SoundSet"                  "Creep_Bad_Engine"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            ""

    "Ability1"                  "upgrade_artillery_tower"
    "Ability2"                  ""

    "AttackDamageMin"           "60"
    "AttackDamageMax"           "65"
    "AttackRange"               "700"
    "AttackAcquisitionRange"    "700"
    "AttackRate"                "2"
    "AttackAnimationPoint"      "0.7"
  
  "AttackType"                "siege"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "250"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }
  
  "artillery_tower"
  {
    "Model"                     "models/props_structures/rock_golem/tower_radiant_rock_golem.vmdl"
    "ModelScale"                "0.7"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/econ/events/ti9/rock_golem_tower/radiant_tower_attack.vpcf"
    "ProjectileSpeed"           "2500"
    "SoundSet"                  "Tower.Water"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            ""

    "Ability1"                  "upgrade_ultimate_artillery_tower"
    "Ability2"                  ""

    "AttackDamageMin"           "350"
    "AttackDamageMax"           "360"
    "AttackRange"               "800"
    "AttackAcquisitionRange"    "800"
    "AttackRate"                "2"
    "AttackAnimationPoint"      "0.6"
  
    "AttackType"                "siege"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "1500"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }
  
  "ultimate_artillery_tower"
  {
    "Model"                     "models/props_structures/rock_golem/tower_dire_rock_golem.vmdl"
    "ModelScale"                "0.7"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/econ/events/ti9/rock_golem_tower/dire_tower_attack.vpcf"
    "ProjectileSpeed"           "2500"
    "SoundSet"                  "Tower.Fire"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            ""

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "1270"
    "AttackDamageMax"           "1280"
    "AttackRange"               "800"
    "AttackAcquisitionRange"    "800"
    "AttackRate"                "2"
    "AttackAnimationPoint"      "0.6"
  
    "AttackType"                "siege"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "3000"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  ////////////////////////////////////
  // Elementals
  ////////////////////////////////////

  "elemental_core"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_fire_pit"
    "Ability2"                  "upgrade_frozen_obelisk"
    "Ability3"                  "upgrade_shock_particle"
    "Ability4"                  "upgrade_light_flies"
    "Ability5"                  "upgrade_poison_well"
    "Ability6"                  "upgrade_splasher"
    "Ability7"                  "upgrade_rockfall"
    "Ability8"                  "upgrade_spellslinger"

    "AttackDamageMin"           "6"
    "AttackDamageMax"           "7"
    "AttackRange"               "600"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "fire_pit"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_magma_well"
    "Ability2"                  ""

    "AttackDamageMin"           "19"
    "AttackDamageMax"           "21"
    "AttackRange"               "400"
    "AttackAcquisitionRange"    "400"
    "AttackRate"                "2.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "magma_well"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_meteor_attractor"
    "Ability2"                  "upgrade_living_flame"
    "Ability3"                  ""

    "AttackDamageMin"           "43"
    "AttackDamageMax"           "48"
    "AttackRange"               "400"
    "AttackAcquisitionRange"    "400"
    "AttackRate"                "2.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "meteor_attractor"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_armageddon"
    "Ability2"                  ""

    "AttackDamageMin"           "90"
    "AttackDamageMax"           "94"
    "AttackRange"               "800"
    "AttackAcquisitionRange"    "800"
    "AttackRate"                "2.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "armageddon"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_moonbeam_projector"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"
    "Ability3"                  ""

    "AttackDamageMin"           "228"
    "AttackDamageMax"           "232"
    "AttackRange"               "800"
    "AttackAcquisitionRange"    "800"
    "AttackRate"                "2.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_moonbeam_projector"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""

    "AttackDamageMin"           "917"
    "AttackDamageMax"           "920"
    "AttackRange"               "800"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "4.0"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "living_flame"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_hellfire"
    "Ability2"                  ""

    "AttackDamageMin"           "74"
    "AttackDamageMax"           "78"
    "AttackRange"               "400"
    "AttackAcquisitionRange"    "400"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "hellfire"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_firelord"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"

    "AttackDamageMin"           "117"
    "AttackDamageMax"           "121"
    "AttackRange"               "400"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.3"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_firelord"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""

    "AttackDamageMin"           "244"
    "AttackDamageMax"           "248"
    "AttackRange"               "500"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.3"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "frozen_obelisk"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_runic_obelisk"
    "Ability2"                  ""

    "AttackDamageMin"           "8"
    "AttackDamageMax"           "10"
    "AttackRange"               "500"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "runic_obelisk"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_frozen_watcher"
    "Ability2"                  "upgrade_icicle"
    "Ability3"                  ""

    "AttackDamageMin"           "29"
    "AttackDamageMax"           "32"
    "AttackRange"               "600"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1.25"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "frozen_watcher"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_frozen_core"
    "Ability2"                  ""

    "AttackDamageMin"           "51"
    "AttackDamageMax"           "54"
    "AttackRange"               "600"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1.25"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "frozen_core"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_lich"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"
    "Ability3"                  ""

    "AttackDamageMin"           "112"
    "AttackDamageMax"           "115"
    "AttackRange"               "600"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_lich"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""

    "AttackDamageMin"           "437"
    "AttackDamageMax"           "441"
    "AttackRange"               "600"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "icicle"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_tricicle"
    "Ability2"                  ""

    "AttackDamageMin"           "68"
    "AttackDamageMax"           "70"
    "AttackRange"               "600"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "tricicle"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_crystal"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"
    "Ability3"                  ""

    "AttackDamageMin"           "115"
    "AttackDamageMax"           "117"
    "AttackRange"               "600"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_crystal"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""

    "AttackDamageMin"           "407"
    "AttackDamageMax"           "414"
    "AttackRange"               "800"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "shock_particle"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_shock_generator"
    "Ability2"                  ""

    "AttackDamageMin"           "5"
    "AttackDamageMax"           "10"
    "AttackRange"               "150"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "shock_generator"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_lightning_beacon"
    "Ability2"                  "upgrade_voltage"
    "Ability3"                  ""

    "AttackDamageMin"           "5"
    "AttackDamageMax"           "10"
    "AttackRange"               "200"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.25"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "lightning_beacon"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_lightning_generator"
    "Ability2"                  ""

    "AttackDamageMin"           "348"
    "AttackDamageMax"           "362"
    "AttackRange"               "900"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "lightning_generator"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_annihilation_glyph"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"
    "Ability3"                  ""

    "AttackDamageMin"           "667"
    "AttackDamageMax"           "681"
    "AttackRange"               "1000"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_annihilation_glyph"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""

    "AttackDamageMin"           "1914"
    "AttackDamageMax"           "1918"
    "AttackRange"               "1000"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "voltage"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_high_voltage"
    "Ability2"                  ""

    "AttackDamageMin"           "10"
    "AttackDamageMax"           "15"
    "AttackRange"               "200"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "high_voltage"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_orb_keeper"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"
    "Ability3"                  ""

    "AttackDamageMin"           "35"
    "AttackDamageMax"           "50"
    "AttackRange"               "200"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_orb_keeper"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "101"
    "AttackDamageMax"           "116"
    "AttackRange"               "225"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "light_flies"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_holy_lantern"
    "Ability2"                  ""

    "AttackDamageMin"           "9"
    "AttackDamageMax"           "12"
    "AttackRange"               "800"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "holy_lantern"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_lightshroom"
    "Ability2"                  "upgrade_sunray_tower"
    "Ability3"                  ""

    "AttackDamageMin"           "23"
    "AttackDamageMax"           "26"
    "AttackRange"               "850"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "lightshroom"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_enchanted_lightshroom"
    "Ability2"                  ""

    "AttackDamageMin"           "143"
    "AttackDamageMax"           "149"
    "AttackRange"               "400"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "enchanted_lightshroom"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ulitmate_enchanted_lightshroom"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"
    "Ability3"                  ""

    "AttackDamageMin"           "384"
    "AttackDamageMax"           "389"
    "AttackRange"               "400"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_enchanted_lightshroom"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "907"
    "AttackDamageMax"           "908"
    "AttackRange"               "400"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "sunray_tower"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_purified_sunray_tower"
    "Ability2"                  ""

    "AttackDamageMin"           "71"
    "AttackDamageMax"           "72"
    "AttackRange"               "900"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "purified_sunray_tower"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ulitmate_northrend_titan_vault"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"

    "AttackDamageMin"           "180"
    "AttackDamageMax"           "181"
    "AttackRange"               "1000"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_northrend_titan_vault"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "435"
    "AttackDamageMax"           "435"
    "AttackRange"               "1000"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "poison_well"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_catacomb"
    "Ability2"                  ""

    "AttackDamageMin"           "11"
    "AttackDamageMax"           "13"
    "AttackRange"               "600"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "catacomb"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_septic_tank"
    "Ability2"                  "upgrade_decayed_guardian"

    "AttackDamageMin"           "31"
    "AttackDamageMax"           "33"
    "AttackRange"               "650"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "septic_tank"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_plague_fanatic"
    "Ability2"                  ""

    "AttackDamageMin"           "51"
    "AttackDamageMax"           "56"
    "AttackRange"               "700"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "plague_fanatic"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_gravedigger"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"

    "AttackDamageMin"           "97"
    "AttackDamageMax"           "101"
    "AttackRange"               "700"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.3"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_gravedigger"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "413"
    "AttackDamageMax"           "416"
    "AttackRange"               "700"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.3"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "decayed_guardian"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_decayed_horror"
    "Ability2"                  ""

    "AttackDamageMin"           "50"
    "AttackDamageMax"           "70"
    "AttackRange"               "300"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "decayed_horror"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_diabolist"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"

    "AttackDamageMin"           "145"
    "AttackDamageMax"           "165"
    "AttackRange"               "300"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_diabolist"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "330"
    "AttackDamageMax"           "360"
    "AttackRange"               "400"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "splasher"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_tidecaller"
    "Ability2"                  ""

    "AttackDamageMin"           "5"
    "AttackDamageMax"           "7"
    "AttackRange"               "500"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "tidecaller"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_water_elemental"
    "Ability2"                  "upgrade_tidal_guardian"

    "AttackDamageMin"           "16"
    "AttackDamageMax"           "18"
    "AttackRange"               "500"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "water_elemental"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_volatile_water_elemental"
    "Ability2"                  ""

    "AttackDamageMin"           "57"
    "AttackDamageMax"           "61"
    "AttackRange"               "500"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "volatile_water_elemental"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_hurricane_elemental"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"

    "AttackDamageMin"           "89"
    "AttackDamageMax"           "93"
    "AttackRange"               "500"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_hurricane_elemental"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "328"
    "AttackDamageMax"           "334"
    "AttackRange"               "500"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "tidal_guardian"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_tidal_monstrosity"
    "Ability2"                  ""

    "AttackDamageMin"           "132"
    "AttackDamageMax"           "148"
    "AttackRange"               "600"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "3"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "tidal_monstrosity"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_sludge_monstrosity"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"

    "AttackDamageMin"           "295"
    "AttackDamageMax"           "331"
    "AttackRange"               "600"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "3"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "normal"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_sludge_monstrosity"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "1507"
    "AttackDamageMax"           "1557"
    "AttackRange"               "600"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "rockfall"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_avalanche"
    "Ability2"                  ""

    "AttackDamageMin"           "8"
    "AttackDamageMax"           "22"
    "AttackRange"               "300"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "siege"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "avalanche"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_earth_protector"
    "Ability2"                  "upgrade_poisonous_roots"

    "AttackDamageMin"           "27"
    "AttackDamageMax"           "68"
    "AttackRange"               "300"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "siege"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "earth_protector"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ancient_earth_protector"
    "Ability2"                  ""

    "AttackDamageMin"           "63"
    "AttackDamageMax"           "141"
    "AttackRange"               "400"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "siege"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ancient_earth_protector"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_ancient_warden"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"

    "AttackDamageMin"           "186"
    "AttackDamageMax"           "338"
    "AttackRange"               "500"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "siege"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_ancient_warden"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "1387"
    "AttackDamageMax"           "1530"
    "AttackRange"               "500"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "2.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "siege"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "poisonous_roots"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_paralyzing_roots"
    "Ability2"                  ""

    "AttackDamageMin"           "105"
    "AttackDamageMax"           "120"
    "AttackRange"               "650"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.7"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "piercing"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "paralyzing_roots"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_scorpion"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"

    "AttackDamageMin"           "224"
    "AttackDamageMax"           "233"
    "AttackRange"               "650"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.7"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "piercing"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_scorpion"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "844"
    "AttackDamageMax"           "871"
    "AttackRange"               "700"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "piercing"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "spellslinger"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_spellslinger_master"
    "Ability2"                  ""

    "AttackDamageMin"           "1"
    "AttackDamageMax"           "2"
    "AttackRange"               "1000"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.3"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "spellslinger_master"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_archmage"
    "Ability2"                  "upgrade_arcane_pylon"

    "AttackDamageMin"           "3"
    "AttackDamageMax"           "5"
    "AttackRange"               "1000"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.25"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "archmage"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_grand_archmage"
    "Ability2"                  ""

    "AttackDamageMin"           "32"
    "AttackDamageMax"           "35"
    "AttackRange"               "800"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "grand_archmage"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_kirin_tor_wizard"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"

    "AttackDamageMin"           "143"
    "AttackDamageMax"           "146"
    "AttackRange"               "800"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_kirin_tor_wizard"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "812"
    "AttackDamageMax"           "815"
    "AttackRange"               "800"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "arcane_pylon"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_unstable_arcane_pylon"
    "Ability2"                  ""

    "AttackDamageMin"           "28"
    "AttackDamageMax"           "30"
    "AttackRange"               "1000"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "unstable_arcane_pylon"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  "upgrade_ultimate_arcane_orb"
    "Ability2"                  "upgrade_ultimate_unstable_elemental_core"

    "AttackDamageMin"           "128"
    "AttackDamageMax"           "130"
    "AttackRange"               "1000"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.5"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_arcane_orb"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "163"
    "AttackDamageMax"           "165"
    "AttackRange"               "1000"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "0.33"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }

  "ultimate_unstable_elemental_core"
  {
    "Model"                     "models/heroes/wisp/wisp.vmdl"
    "ModelScale"                "1.0"
    "ModelRotation"             "0"
    "ModelOffset"               "1"
    "PedestalModel"             "models/props_teams/logo_teams_tintable.vmdl"
    "PedestalModelScale"        "0.5"
    "PedestalOffset"            "5"
    "ProjectileModel"           "particles/units/heroes/hero_wisp/wisp_base_attack.vpcf"
    "ProjectileSpeed"           "1200"
    "SoundSet"                  "Hero_Wisp"
    "MinimapIconSize"           "10"
    "GameSoundsFile"            "soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts"

    "Ability1"                  ""
    "Ability2"                  ""

    "AttackDamageMin"           "650"
    "AttackDamageMax"           "680"
    "AttackRange"               "700"
    "AttackAcquisitionRange"    "600"
    "AttackRate"                "1"
    "AttackAnimationPoint"      "0.15"
    
    "AttackType"                "chaos"

    "BaseClass"                 "npc_dota_creature"
    "BoundsHullName"            "DOTA_HULL_SIZE_BUILDING"
    "AttackCapabilities"        "DOTA_UNIT_CAP_RANGED_ATTACK"
    "MovementCapabilities"      "DOTA_UNIT_CAP_MOVE_NONE"
    "StatusHealth"              "75"
    "ArmorPhysical"             "5.0"

    "BuildTime"                 "1"
    "ConstructionSize"          "2"
    "BlockPathingSize"          "2"
  }
}