return {
  {
    {
      itemname = "item_radiant_creep",
      unit = "radiant_creep",
      cost = 5,
      income = 1,
      initial_cd = 25,
      cd = 3,
      max_stock = 32,
    },
    {
      itemname = "item_night_wolf",
      unit = "night_wolf",
      cost = 10,
      income = 2,
      initial_cd = 40,
      cd = 3,
      max_stock = 32,
    },
    {
      itemname = "item_zombie",
      unit = "zombie",
      cost = 20,
      income = 3,
      initial_cd = 55,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_eidolon",
      unit = "eidolon",
      cost = 35,
      income = 5,
      initial_cd = 70,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_treant",
      unit = "treant",
      cost = 50,
      income = 6,
      initial_cd = 85,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_ghoul",
      unit = "ghoul",
      cost = 70,
      income = 8,
      initial_cd = 100,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_kobold",
      unit = "kobold",
      cost = 100,
      income = 11,
      initial_cd = 115,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_wildkin_small",
      unit = "wildkin_small",
      cost = 150,
      income = 15,
      initial_cd = 130,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_vhoul",
      unit = "vhoul",
      cost = 200,
      income = 18,
      initial_cd = 145,
      cd = 5,
      max_stock = 16,
    },
    {
      itemname = "item_potato",
      unit = "potato",
      cost = 350,
      income = 32,
      initial_cd = 160,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_storm_panda",
      unit = "storm_panda",
      cost = 750,
      income = 25,
      initial_cd = 200,
      cd = 5,
      max_stock = 16,
    },
    {
      itemname = "item_necro_warrior",
      unit = "necro_warrior",
      cost = 1000,
      income = 75,
      initial_cd = 250,
      cd = 10,
      max_stock = 8,
    },
  },
  {
    {
      itemname = "item_dire_creep",
      unit = "dire_creep",
      cost = 1000,
      income = 100,
      initial_cd = 300,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_wolf",
      unit = "wolf",
      cost = 2250,
      income = 200,
      initial_cd = 330,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_angry_centaur",
      unit = "angry_centaur",
      cost = 4000,
      income = 335,
      initial_cd = 360,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_satyr",
      unit = "satyr",
      cost = 7500,
      income = 600,
      initial_cd = 390,
      cd = 5,
      max_stock = 16,
    },
    {
      itemname = "item_ogre_magi",
      unit = "ogre_magi",
      cost = 10000,
      income = 750,
      initial_cd = 420,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_ghost_creep",
      unit = "ghost",
      cost = 12000,
      income = 950,
      initial_cd = 450,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_kobold_taskmaster",
      unit = "kobold_taskmaster",
      cost = 15000,
      income = 1225,
      initial_cd = 480,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_wildkin",
      unit = "wildkin",
      cost = 20000,
      income = 1500,
      initial_cd = 510,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_mud_golem",
      unit = "mud_golem",
      cost = 30000,
      income = 2000,
      initial_cd = 540,
      cd = 5,
      max_stock = 16,
    },
    {
      itemname = "item_tomato",
      unit = "tomato",
      cost = 50000,
      income = 1250,
      initial_cd = 600,
      cd = 5,
      max_stock = 16,
    },
    {
      itemname = "item_earth_panda",
      unit = "earth_panda",
      cost = 65000,
      income = 3500,
      initial_cd = 650,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_stone_golem",
      unit = "stone_golem",
      cost = 100000,
      income = 4750,
      initial_cd = 700,
      cd = 10,
      max_stock = 8,
    }, 
  },
  {
    {
      itemname = "item_necro_archer",
      unit = "necro_archer",
      cost = 35000,
      income = -2500,
      initial_cd = 800,
      cd = 5,
      max_stock = 16,
    },
    {
      itemname = "item_bear",
      unit = "bear",
      cost = 62500,
      income = 3125,
      initial_cd = 830,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_happy_centaur",
      unit = "happy_centaur",
      cost = 75000,
      income = 3750,
      initial_cd = 860,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_satyr_warlord",
      unit = "satyr_warlord",
      cost = 100000,
      income = 5000,
      initial_cd = 890,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_ogre",
      unit = "ogre",
      cost = 112500,
      income = 5250,
      initial_cd = 920,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_infernal",
      unit = "infernal",
      cost = 125000,
      income = 6250,
      initial_cd = 950,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_blue_lizard",
      unit = "blue_lizard",
      cost = 150000,
      income = 7250,
      initial_cd = 1000,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_red_lizard",
      unit = "red_lizard",
      cost = 162500,
      income = 7500,
      initial_cd = 1050,
      cd = 5,
      max_stock = 16,
    },
    {
      itemname = "item_prowler",
      unit = "prowler",
      cost = 200000,
      income = 8750,
      initial_cd = 1100,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_dragon",
      unit = "dragon",
      cost = 300000,
      income = -20000,
      initial_cd = 1200,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_fire_panda",
      unit = "fire_panda",
      cost = 1000000,
      income = -50000,
      initial_cd = 1300,
      cd = 5,
      max_stock = 32,
    },
    {
      itemname = "item_roshan",
      unit = "roshan",
      cost = 2250000,
      income = -100000,
      initial_cd = 1500,
      cd = 10,
      max_stock = 8,
    },  
  },
}
