return {
  {
    {
      itemname = "item_radiant_creep",
      unit = "radiant_creep",
      cost = 5,
      income = 1,
      initial_cd = 0,
      cd = 3,
    },
    {
      itemname = "item_night_wolf",
      unit = "night_wolf",
      cost = 10,
      income = 2,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_zombie",
      unit = "zombie",
      cost = 20,
      income = 3,
      initial_cd = 0,
      cd = 9,
    },
    {
      itemname = "item_eidolon",
      unit = "eidolon",
      cost = 35,
      income = 5,
      initial_cd = 0,
      cd = 10,
    },
    {
      itemname = "item_treant",
      unit = "treant",
      cost = 50,
      income = 6,
      initial_cd = 0,
      cd = 11,
    },
    {
      itemname = "item_ghoul",
      unit = "ghoul",
      cost = 70,
      income = 8,
      initial_cd = 0,
      cd = 12,
    },
    {
      itemname = "item_kobold",
      unit = "kobold",
      cost = 100,
      income = 11,
      initial_cd = 0,
      cd = 13,
    },
    {
      itemname = "item_wildkin_small",
      unit = "wildkin_small",
      cost = 150,
      income = 15,
      initial_cd = 0,
      cd = 15,
    },
    {
      itemname = "item_vhoul",
      unit = "vhoul",
      cost = 200,
      income = 18,
      initial_cd = 0,
      cd = 16,
    },
    {
      itemname = "item_potato",
      unit = "potato",
      cost = 350,
      income = 1,
      initial_cd = 0,
      cd = 17,
    },
    {
      itemname = "item_storm_panda",
      unit = "storm_panda",
      cost = 750,
      income = 1,
      initial_cd = 0,
      cd = 18,
    },
    {
      itemname = "item_necro_warrior",
      unit = "necro_warrior",
      cost = 1000,
      income = 75,
      initial_cd = 0,
      cd = 20,
    },
  },
  {
    {
      itemname = "item_dire_creep",
      unit = "dire_creep",
      cost = 1000,
      income = 100,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_wolf",
      unit = "wolf",
      cost = 2250,
      income = 200,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_angry_centaur",
      unit = "angry_centaur",
      cost = 4000,
      income = 335,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_satyr",
      unit = "satyr",
      cost = 7500,
      income = 600,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_ogre_magi",
      unit = "ogre_magi",
      cost = 1000,
      income = 100,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_ghost",
      unit = "ghost",
      cost = 2250,
      income = 200,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_kobold_taskmaster",
      unit = "kobold_taskmaster",
      cost = 4000,
      income = 335,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_wildkin",
      unit = "wildkin",
      cost = 7500,
      income = 600,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_mud_golem",
      unit = "mud_golem",
      cost = 1000,
      income = 100,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_tomato",
      unit = "tomato",
      cost = 2250,
      income = 200,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_earth_panda",
      unit = "earth_panda",
      cost = 4000,
      income = 335,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_stone_golem",
      unit = "stone_golem",
      cost = 7500,
      income = 600,
      initial_cd = 0,
      cd = 5,
    }, 
  },
  {
    {
      itemname = "item_necro_archer",
      unit = "necro_archer",
      cost = 1000,
      income = 100,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_bear",
      unit = "bear",
      cost = 2250,
      income = 200,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_happy_centaur",
      unit = "happy_centaur",
      cost = 4000,
      income = 335,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_satyr_warlord",
      unit = "satyr_warlord",
      cost = 7500,
      income = 600,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_ogre",
      unit = "ogre",
      cost = 1000,
      income = 100,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_infernal",
      unit = "infernal",
      cost = 2250,
      income = 200,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_blue_lizard",
      unit = "blue_lizard",
      cost = 4000,
      income = 335,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_red_lizard",
      unit = "red_lizard",
      cost = 7500,
      income = 600,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_prowler",
      unit = "prowler",
      cost = 1000,
      income = 100,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_dragon",
      unit = "dragon",
      cost = 2250,
      income = 200,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_fire_panda",
      unit = "fire_panda",
      cost = 4000,
      income = 335,
      initial_cd = 0,
      cd = 5,
    },
    {
      itemname = "item_roshan",
      unit = "roshan",
      cost = 7500,
      income = 600,
      initial_cd = 0,
      cd = 5,
    },  
  },
}

